#!/bin/bash
counter=$1
counter=$(( counter * 60 ))

minusome(){
	counter=$(( counter - 1 ))
}

while [ $counter -gt 0 ]
do
	echo $counter seconds remaining
	minusome
done

[ $counter = 0 ] && echo out of time && minusome

while true
do
	echo you are ${counter#*-} seconds late
	minusome
	[ $counter = -30 ]  && break  
done
